const subPackages = [
  {
    root: 'base',
    pages: [
      'pages/button/index',
      'pages/cell/index',
      'pages/configprovider/index',
      'pages/icon/index',
      'pages/overlay/index',
      'pages/popup/index',
    ],
  },
  {
    root: 'layout',
    pages: [
      'pages/divider/index',
      'pages/grid/index',
      'pages/layout/index',
      'pages/sticky/index',
    ],
  },
  {
    root: 'nav',
    pages: [
      'pages/elevator/index',
      'pages/fixednav/index',
      'pages/indicator/index',
      'pages/menu/index',
      'pages/navbar/index',
      'pages/pagination/index',
      'pages/sidenavbar/index',
      'pages/tabbar/index',
      'pages/tabs/index',
    ],
  },
  {
    root: 'dentry',
    pages: [
      'pages/calendar/index',
      'pages/cascader/index',
      'pages/checkbox/index',
      'pages/datepicker/index',
      'pages/input/index',
      'pages/inputnumber/index',
      'pages/numberkeyboard/index',
      'pages/picker/index',
      'pages/radio/index',
      'pages/range/index',
      'pages/rate/index',
      'pages/searchbar/index',
      'pages/shortpassword/index',
      'pages/textarea/index',
      'pages/uploader/index',
    ],
  },
  {
    root: 'feedback',
    pages: [
      'pages/actionsheet/index',
      'pages/backtop/index',
      'pages/dialog/index',
      'pages/drag/index',
      'pages/infiniteloading/index',
      'pages/notify/index',
      'pages/swipe/index',
      'pages/switch/index',
      'pages/toast/index',
    ],
  },
  {
    root: 'exhibition',
    pages: [
      'pages/animate/index',
      'pages/animatingnumbers/index',
      'pages/avatar/index',
      'pages/badge/index',
      'pages/circleprogress/index',
      'pages/collapse/index',
      'pages/countdown/index',
      'pages/ellipsis/index',
      'pages/empty/index',
      'pages/imagepreview/index',
      'pages/noticebar/index',
      'pages/popover/index',
      'pages/price/index',
      'pages/progress/index',
      'pages/skeleton/index',
      'pages/steps/index',
      'pages/swiper/index',
      'pages/table/index',
      'pages/tag/index',
      'pages/trendarrow/index',
      'pages/virtuallist/index',
      'pages/watermark/index',
    ],
  },
  {
    root: 'business',
    pages: [
      'pages/address/index',
      'pages/barrage/index',
      'pages/card/index',
      'pages/signature/index',
      'pages/timeselect/index',
    ],
  },
]

export default defineAppConfig({
  pages: ['pages/index/index'],
  subPackages,
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'NutUI-React',
    navigationBarTextStyle: 'black',
  },
})
