import ButtonzhTW from '@/packages/button/doc.zh-TW.md?raw';
import Buttontaro from '@/packages/button/doc.taro.md?raw';
import ButtonenUS from '@/packages/button/doc.en-US.md?raw';
import Button from '@/packages/button/doc.md?raw'
import CellzhTW from '@/packages/cell/doc.zh-TW.md?raw';
import Celltaro from '@/packages/cell/doc.taro.md?raw';
import CellenUS from '@/packages/cell/doc.en-US.md?raw';
import Cell from '@/packages/cell/doc.md?raw'
import CellGroup from '@/packages/cellgroup/doc.md?raw'
import ConfigProviderzhTW from '@/packages/configprovider/doc.zh-TW.md?raw';
import ConfigProvidertaro from '@/packages/configprovider/doc.taro.md?raw';
import ConfigProviderenUS from '@/packages/configprovider/doc.en-US.md?raw';
import ConfigProvider from '@/packages/configprovider/doc.md?raw'
import ImagezhTW from '@/packages/image/doc.zh-TW.md?raw';
import Imagetaro from '@/packages/image/doc.taro.md?raw';
import ImageenUS from '@/packages/image/doc.en-US.md?raw';
import Image from '@/packages/image/doc.md?raw'
import OverlayzhTW from '@/packages/overlay/doc.zh-TW.md?raw';
import Overlaytaro from '@/packages/overlay/doc.taro.md?raw';
import OverlayenUS from '@/packages/overlay/doc.en-US.md?raw';
import Overlay from '@/packages/overlay/doc.md?raw'
import Col from '@/packages/col/doc.md?raw'
import DividerzhTW from '@/packages/divider/doc.zh-TW.md?raw';
import Dividertaro from '@/packages/divider/doc.taro.md?raw';
import DividerenUS from '@/packages/divider/doc.en-US.md?raw';
import Divider from '@/packages/divider/doc.md?raw'
import GridzhTW from '@/packages/grid/doc.zh-TW.md?raw';
import Gridtaro from '@/packages/grid/doc.taro.md?raw';
import GridenUS from '@/packages/grid/doc.en-US.md?raw';
import Grid from '@/packages/grid/doc.md?raw'
import GridItem from '@/packages/griditem/doc.md?raw'
import LayoutzhTW from '@/packages/layout/doc.zh-TW.md?raw';
import Layouttaro from '@/packages/layout/doc.taro.md?raw';
import LayoutenUS from '@/packages/layout/doc.en-US.md?raw';
import Layout from '@/packages/layout/doc.md?raw'
import Row from '@/packages/row/doc.md?raw'
import SpacezhTW from '@/packages/space/doc.zh-TW.md?raw';
import Spacetaro from '@/packages/space/doc.taro.md?raw';
import SpaceenUS from '@/packages/space/doc.en-US.md?raw';
import Space from '@/packages/space/doc.md?raw'
import StickyzhTW from '@/packages/sticky/doc.zh-TW.md?raw';
import Stickytaro from '@/packages/sticky/doc.taro.md?raw';
import StickyenUS from '@/packages/sticky/doc.en-US.md?raw';
import Sticky from '@/packages/sticky/doc.md?raw'
import SafeAreazhTW from '@/packages/safearea/doc.zh-TW.md?raw';
import SafeAreataro from '@/packages/safearea/doc.taro.md?raw';
import SafeAreaenUS from '@/packages/safearea/doc.en-US.md?raw';
import SafeArea from '@/packages/safearea/doc.md?raw'
import BackTopzhTW from '@/packages/backtop/doc.zh-TW.md?raw';
import BackToptaro from '@/packages/backtop/doc.taro.md?raw';
import BackTopenUS from '@/packages/backtop/doc.en-US.md?raw';
import BackTop from '@/packages/backtop/doc.md?raw'
import ElevatorzhTW from '@/packages/elevator/doc.zh-TW.md?raw';
import Elevatortaro from '@/packages/elevator/doc.taro.md?raw';
import ElevatorenUS from '@/packages/elevator/doc.en-US.md?raw';
import Elevator from '@/packages/elevator/doc.md?raw'
import FixedNavzhTW from '@/packages/fixednav/doc.zh-TW.md?raw';
import FixedNavtaro from '@/packages/fixednav/doc.taro.md?raw';
import FixedNavenUS from '@/packages/fixednav/doc.en-US.md?raw';
import FixedNav from '@/packages/fixednav/doc.md?raw'
import NavBarzhTW from '@/packages/navbar/doc.zh-TW.md?raw';
import NavBartaro from '@/packages/navbar/doc.taro.md?raw';
import NavBarenUS from '@/packages/navbar/doc.en-US.md?raw';
import NavBar from '@/packages/navbar/doc.md?raw'
import SideNavBarzhTW from '@/packages/sidenavbar/doc.zh-TW.md?raw';
import SideNavBartaro from '@/packages/sidenavbar/doc.taro.md?raw';
import SideNavBarenUS from '@/packages/sidenavbar/doc.en-US.md?raw';
import SideNavBar from '@/packages/sidenavbar/doc.md?raw'
import SideNavBarItem from '@/packages/sidenavbaritem/doc.md?raw'
import SubSideNavBar from '@/packages/subsidenavbar/doc.md?raw'
import TabbarzhTW from '@/packages/tabbar/doc.zh-TW.md?raw';
import Tabbartaro from '@/packages/tabbar/doc.taro.md?raw';
import TabbarenUS from '@/packages/tabbar/doc.en-US.md?raw';
import Tabbar from '@/packages/tabbar/doc.md?raw'
import TabbarItem from '@/packages/tabbaritem/doc.md?raw'
import TabPane from '@/packages/tabpane/doc.md?raw'
import TabszhTW from '@/packages/tabs/doc.zh-TW.md?raw';
import Tabstaro from '@/packages/tabs/doc.taro.md?raw';
import TabsenUS from '@/packages/tabs/doc.en-US.md?raw';
import Tabs from '@/packages/tabs/doc.md?raw'
import AddresszhTW from '@/packages/address/doc.zh-TW.md?raw';
import Addresstaro from '@/packages/address/doc.taro.md?raw';
import AddressenUS from '@/packages/address/doc.en-US.md?raw';
import Address from '@/packages/address/doc.md?raw'
import CalendarzhTW from '@/packages/calendar/doc.zh-TW.md?raw';
import Calendartaro from '@/packages/calendar/doc.taro.md?raw';
import CalendarenUS from '@/packages/calendar/doc.en-US.md?raw';
import Calendar from '@/packages/calendar/doc.md?raw'
import CalendarItem from '@/packages/calendaritem/doc.md?raw'
import CalendarCardzhTW from '@/packages/calendarcard/doc.zh-TW.md?raw';
import CalendarCardtaro from '@/packages/calendarcard/doc.taro.md?raw';
import CalendarCardenUS from '@/packages/calendarcard/doc.en-US.md?raw';
import CalendarCard from '@/packages/calendarcard/doc.md?raw'
import CascaderzhTW from '@/packages/cascader/doc.zh-TW.md?raw';
import Cascadertaro from '@/packages/cascader/doc.taro.md?raw';
import CascaderenUS from '@/packages/cascader/doc.en-US.md?raw';
import Cascader from '@/packages/cascader/doc.md?raw'
import CheckboxzhTW from '@/packages/checkbox/doc.zh-TW.md?raw';
import Checkboxtaro from '@/packages/checkbox/doc.taro.md?raw';
import CheckboxenUS from '@/packages/checkbox/doc.en-US.md?raw';
import Checkbox from '@/packages/checkbox/doc.md?raw'
import CheckboxGroup from '@/packages/checkboxgroup/doc.md?raw'
import DatePickerzhTW from '@/packages/datepicker/doc.zh-TW.md?raw';
import DatePickertaro from '@/packages/datepicker/doc.taro.md?raw';
import DatePickerenUS from '@/packages/datepicker/doc.en-US.md?raw';
import DatePicker from '@/packages/datepicker/doc.md?raw'
import FormzhTW from '@/packages/form/doc.zh-TW.md?raw';
import Formtaro from '@/packages/form/doc.taro.md?raw';
import FormenUS from '@/packages/form/doc.en-US.md?raw';
import Form from '@/packages/form/doc.md?raw'
import FormItem from '@/packages/formitem/doc.md?raw'
import InputzhTW from '@/packages/input/doc.zh-TW.md?raw';
import Inputtaro from '@/packages/input/doc.taro.md?raw';
import InputenUS from '@/packages/input/doc.en-US.md?raw';
import Input from '@/packages/input/doc.md?raw'
import InputNumberzhTW from '@/packages/inputnumber/doc.zh-TW.md?raw';
import InputNumbertaro from '@/packages/inputnumber/doc.taro.md?raw';
import InputNumberenUS from '@/packages/inputnumber/doc.en-US.md?raw';
import InputNumber from '@/packages/inputnumber/doc.md?raw'
import MenuzhTW from '@/packages/menu/doc.zh-TW.md?raw';
import Menutaro from '@/packages/menu/doc.taro.md?raw';
import MenuenUS from '@/packages/menu/doc.en-US.md?raw';
import Menu from '@/packages/menu/doc.md?raw'
import MenuItem from '@/packages/menuitem/doc.md?raw'
import NumberKeyboardzhTW from '@/packages/numberkeyboard/doc.zh-TW.md?raw';
import NumberKeyboardtaro from '@/packages/numberkeyboard/doc.taro.md?raw';
import NumberKeyboardenUS from '@/packages/numberkeyboard/doc.en-US.md?raw';
import NumberKeyboard from '@/packages/numberkeyboard/doc.md?raw'
import PickerzhTW from '@/packages/picker/doc.zh-TW.md?raw';
import Pickertaro from '@/packages/picker/doc.taro.md?raw';
import PickerenUS from '@/packages/picker/doc.en-US.md?raw';
import Picker from '@/packages/picker/doc.md?raw'
import RadiozhTW from '@/packages/radio/doc.zh-TW.md?raw';
import Radiotaro from '@/packages/radio/doc.taro.md?raw';
import RadioenUS from '@/packages/radio/doc.en-US.md?raw';
import Radio from '@/packages/radio/doc.md?raw'
import RadioGroup from '@/packages/radiogroup/doc.md?raw'
import RangezhTW from '@/packages/range/doc.zh-TW.md?raw';
import Rangetaro from '@/packages/range/doc.taro.md?raw';
import RangeenUS from '@/packages/range/doc.en-US.md?raw';
import Range from '@/packages/range/doc.md?raw'
import RatezhTW from '@/packages/rate/doc.zh-TW.md?raw';
import Ratetaro from '@/packages/rate/doc.taro.md?raw';
import RateenUS from '@/packages/rate/doc.en-US.md?raw';
import Rate from '@/packages/rate/doc.md?raw'
import SearchBarzhTW from '@/packages/searchbar/doc.zh-TW.md?raw';
import SearchBartaro from '@/packages/searchbar/doc.taro.md?raw';
import SearchBarenUS from '@/packages/searchbar/doc.en-US.md?raw';
import SearchBar from '@/packages/searchbar/doc.md?raw'
import ShortPasswordzhTW from '@/packages/shortpassword/doc.zh-TW.md?raw';
import ShortPasswordtaro from '@/packages/shortpassword/doc.taro.md?raw';
import ShortPasswordenUS from '@/packages/shortpassword/doc.en-US.md?raw';
import ShortPassword from '@/packages/shortpassword/doc.md?raw'
import SignaturezhTW from '@/packages/signature/doc.zh-TW.md?raw';
import Signaturetaro from '@/packages/signature/doc.taro.md?raw';
import SignatureenUS from '@/packages/signature/doc.en-US.md?raw';
import Signature from '@/packages/signature/doc.md?raw'
import SwitchzhTW from '@/packages/switch/doc.zh-TW.md?raw';
import Switchtaro from '@/packages/switch/doc.taro.md?raw';
import SwitchenUS from '@/packages/switch/doc.en-US.md?raw';
import Switch from '@/packages/switch/doc.md?raw'
import TextAreazhTW from '@/packages/textarea/doc.zh-TW.md?raw';
import TextAreataro from '@/packages/textarea/doc.taro.md?raw';
import TextAreaenUS from '@/packages/textarea/doc.en-US.md?raw';
import TextArea from '@/packages/textarea/doc.md?raw'
import UploaderzhTW from '@/packages/uploader/doc.zh-TW.md?raw';
import Uploadertaro from '@/packages/uploader/doc.taro.md?raw';
import UploaderenUS from '@/packages/uploader/doc.en-US.md?raw';
import Uploader from '@/packages/uploader/doc.md?raw'
import ActionSheetzhTW from '@/packages/actionsheet/doc.zh-TW.md?raw';
import ActionSheettaro from '@/packages/actionsheet/doc.taro.md?raw';
import ActionSheetenUS from '@/packages/actionsheet/doc.en-US.md?raw';
import ActionSheet from '@/packages/actionsheet/doc.md?raw'
import BadgezhTW from '@/packages/badge/doc.zh-TW.md?raw';
import Badgetaro from '@/packages/badge/doc.taro.md?raw';
import BadgeenUS from '@/packages/badge/doc.en-US.md?raw';
import Badge from '@/packages/badge/doc.md?raw'
import DialogzhTW from '@/packages/dialog/doc.zh-TW.md?raw';
import Dialogtaro from '@/packages/dialog/doc.taro.md?raw';
import DialogenUS from '@/packages/dialog/doc.en-US.md?raw';
import Dialog from '@/packages/dialog/doc.md?raw'
import DragzhTW from '@/packages/drag/doc.zh-TW.md?raw';
import Dragtaro from '@/packages/drag/doc.taro.md?raw';
import DragenUS from '@/packages/drag/doc.en-US.md?raw';
import Drag from '@/packages/drag/doc.md?raw'
import EmptyzhTW from '@/packages/empty/doc.zh-TW.md?raw';
import Emptytaro from '@/packages/empty/doc.taro.md?raw';
import EmptyenUS from '@/packages/empty/doc.en-US.md?raw';
import Empty from '@/packages/empty/doc.md?raw'
import InfiniteLoadingzhTW from '@/packages/infiniteloading/doc.zh-TW.md?raw';
import InfiniteLoadingtaro from '@/packages/infiniteloading/doc.taro.md?raw';
import InfiniteLoadingenUS from '@/packages/infiniteloading/doc.en-US.md?raw';
import InfiniteLoading from '@/packages/infiniteloading/doc.md?raw'
import LoadingzhTW from '@/packages/loading/doc.zh-TW.md?raw';
import Loadingtaro from '@/packages/loading/doc.taro.md?raw';
import LoadingenUS from '@/packages/loading/doc.en-US.md?raw';
import Loading from '@/packages/loading/doc.md?raw'
import NoticeBarzhTW from '@/packages/noticebar/doc.zh-TW.md?raw';
import NoticeBartaro from '@/packages/noticebar/doc.taro.md?raw';
import NoticeBarenUS from '@/packages/noticebar/doc.en-US.md?raw';
import NoticeBar from '@/packages/noticebar/doc.md?raw'
import NotifyzhTW from '@/packages/notify/doc.zh-TW.md?raw';
import Notifytaro from '@/packages/notify/doc.taro.md?raw';
import NotifyenUS from '@/packages/notify/doc.en-US.md?raw';
import Notify from '@/packages/notify/doc.md?raw'
import PopoverzhTW from '@/packages/popover/doc.zh-TW.md?raw';
import Popovertaro from '@/packages/popover/doc.taro.md?raw';
import PopoverenUS from '@/packages/popover/doc.en-US.md?raw';
import Popover from '@/packages/popover/doc.md?raw'
import PopupzhTW from '@/packages/popup/doc.zh-TW.md?raw';
import Popuptaro from '@/packages/popup/doc.taro.md?raw';
import PopupenUS from '@/packages/popup/doc.en-US.md?raw';
import Popup from '@/packages/popup/doc.md?raw'
import PullToRefreshzhTW from '@/packages/pulltorefresh/doc.zh-TW.md?raw';
import PullToRefreshtaro from '@/packages/pulltorefresh/doc.taro.md?raw';
import PullToRefreshenUS from '@/packages/pulltorefresh/doc.en-US.md?raw';
import PullToRefresh from '@/packages/pulltorefresh/doc.md?raw'
import SkeletonzhTW from '@/packages/skeleton/doc.zh-TW.md?raw';
import Skeletontaro from '@/packages/skeleton/doc.taro.md?raw';
import SkeletonenUS from '@/packages/skeleton/doc.en-US.md?raw';
import Skeleton from '@/packages/skeleton/doc.md?raw'
import SwipezhTW from '@/packages/swipe/doc.zh-TW.md?raw';
import Swipetaro from '@/packages/swipe/doc.taro.md?raw';
import SwipeenUS from '@/packages/swipe/doc.en-US.md?raw';
import Swipe from '@/packages/swipe/doc.md?raw'
import ToastzhTW from '@/packages/toast/doc.zh-TW.md?raw';
import Toasttaro from '@/packages/toast/doc.taro.md?raw';
import ToastenUS from '@/packages/toast/doc.en-US.md?raw';
import Toast from '@/packages/toast/doc.md?raw'
import AnimatezhTW from '@/packages/animate/doc.zh-TW.md?raw';
import Animatetaro from '@/packages/animate/doc.taro.md?raw';
import AnimateenUS from '@/packages/animate/doc.en-US.md?raw';
import Animate from '@/packages/animate/doc.md?raw'
import AnimatingNumberszhTW from '@/packages/animatingnumbers/doc.zh-TW.md?raw';
import AnimatingNumberstaro from '@/packages/animatingnumbers/doc.taro.md?raw';
import AnimatingNumbersenUS from '@/packages/animatingnumbers/doc.en-US.md?raw';
import AnimatingNumbers from '@/packages/animatingnumbers/doc.md?raw'
import AudiozhTW from '@/packages/audio/doc.zh-TW.md?raw';
import Audiotaro from '@/packages/audio/doc.taro.md?raw';
import AudioenUS from '@/packages/audio/doc.en-US.md?raw';
import Audio from '@/packages/audio/doc.md?raw'
import AvatarzhTW from '@/packages/avatar/doc.zh-TW.md?raw';
import Avatartaro from '@/packages/avatar/doc.taro.md?raw';
import AvatarenUS from '@/packages/avatar/doc.en-US.md?raw';
import Avatar from '@/packages/avatar/doc.md?raw'
import AvatarGroup from '@/packages/avatargroup/doc.md?raw'
import CircleProgresszhTW from '@/packages/circleprogress/doc.zh-TW.md?raw';
import CircleProgresstaro from '@/packages/circleprogress/doc.taro.md?raw';
import CircleProgressenUS from '@/packages/circleprogress/doc.en-US.md?raw';
import CircleProgress from '@/packages/circleprogress/doc.md?raw'
import CollapsezhTW from '@/packages/collapse/doc.zh-TW.md?raw';
import Collapsetaro from '@/packages/collapse/doc.taro.md?raw';
import CollapseenUS from '@/packages/collapse/doc.en-US.md?raw';
import Collapse from '@/packages/collapse/doc.md?raw'
import CollapseItem from '@/packages/collapseitem/doc.md?raw'
import CountDownzhTW from '@/packages/countdown/doc.zh-TW.md?raw';
import CountDowntaro from '@/packages/countdown/doc.taro.md?raw';
import CountDownenUS from '@/packages/countdown/doc.en-US.md?raw';
import CountDown from '@/packages/countdown/doc.md?raw'
import EllipsiszhTW from '@/packages/ellipsis/doc.zh-TW.md?raw';
import Ellipsistaro from '@/packages/ellipsis/doc.taro.md?raw';
import EllipsisenUS from '@/packages/ellipsis/doc.en-US.md?raw';
import Ellipsis from '@/packages/ellipsis/doc.md?raw'
import ImagePreviewzhTW from '@/packages/imagepreview/doc.zh-TW.md?raw';
import ImagePreviewtaro from '@/packages/imagepreview/doc.taro.md?raw';
import ImagePreviewenUS from '@/packages/imagepreview/doc.en-US.md?raw';
import ImagePreview from '@/packages/imagepreview/doc.md?raw'
import IndicatorzhTW from '@/packages/indicator/doc.zh-TW.md?raw';
import Indicatortaro from '@/packages/indicator/doc.taro.md?raw';
import IndicatorenUS from '@/packages/indicator/doc.en-US.md?raw';
import Indicator from '@/packages/indicator/doc.md?raw'
import PaginationzhTW from '@/packages/pagination/doc.zh-TW.md?raw';
import Paginationtaro from '@/packages/pagination/doc.taro.md?raw';
import PaginationenUS from '@/packages/pagination/doc.en-US.md?raw';
import Pagination from '@/packages/pagination/doc.md?raw'
import PricezhTW from '@/packages/price/doc.zh-TW.md?raw';
import Pricetaro from '@/packages/price/doc.taro.md?raw';
import PriceenUS from '@/packages/price/doc.en-US.md?raw';
import Price from '@/packages/price/doc.md?raw'
import ProgresszhTW from '@/packages/progress/doc.zh-TW.md?raw';
import Progresstaro from '@/packages/progress/doc.taro.md?raw';
import ProgressenUS from '@/packages/progress/doc.en-US.md?raw';
import Progress from '@/packages/progress/doc.md?raw'
import Step from '@/packages/step/doc.md?raw'
import StepszhTW from '@/packages/steps/doc.zh-TW.md?raw';
import Stepstaro from '@/packages/steps/doc.taro.md?raw';
import StepsenUS from '@/packages/steps/doc.en-US.md?raw';
import Steps from '@/packages/steps/doc.md?raw'
import SwiperzhTW from '@/packages/swiper/doc.zh-TW.md?raw';
import Swipertaro from '@/packages/swiper/doc.taro.md?raw';
import SwiperenUS from '@/packages/swiper/doc.en-US.md?raw';
import Swiper from '@/packages/swiper/doc.md?raw'
import SwiperItem from '@/packages/swiperitem/doc.md?raw'
import TablezhTW from '@/packages/table/doc.zh-TW.md?raw';
import Tabletaro from '@/packages/table/doc.taro.md?raw';
import TableenUS from '@/packages/table/doc.en-US.md?raw';
import Table from '@/packages/table/doc.md?raw'
import TagzhTW from '@/packages/tag/doc.zh-TW.md?raw';
import Tagtaro from '@/packages/tag/doc.taro.md?raw';
import TagenUS from '@/packages/tag/doc.en-US.md?raw';
import Tag from '@/packages/tag/doc.md?raw'
import TourzhTW from '@/packages/tour/doc.zh-TW.md?raw';
import Tourtaro from '@/packages/tour/doc.taro.md?raw';
import TourenUS from '@/packages/tour/doc.en-US.md?raw';
import Tour from '@/packages/tour/doc.md?raw'
import VideozhTW from '@/packages/video/doc.zh-TW.md?raw';
import Videotaro from '@/packages/video/doc.taro.md?raw';
import VideoenUS from '@/packages/video/doc.en-US.md?raw';
import Video from '@/packages/video/doc.md?raw'
import VirtualListzhTW from '@/packages/virtuallist/doc.zh-TW.md?raw';
import VirtualListtaro from '@/packages/virtuallist/doc.taro.md?raw';
import VirtualListenUS from '@/packages/virtuallist/doc.en-US.md?raw';
import VirtualList from '@/packages/virtuallist/doc.md?raw'
import BarragezhTW from '@/packages/barrage/doc.zh-TW.md?raw';
import Barragetaro from '@/packages/barrage/doc.taro.md?raw';
import BarrageenUS from '@/packages/barrage/doc.en-US.md?raw';
import Barrage from '@/packages/barrage/doc.md?raw'
import CardzhTW from '@/packages/card/doc.zh-TW.md?raw';
import Cardtaro from '@/packages/card/doc.taro.md?raw';
import CardenUS from '@/packages/card/doc.en-US.md?raw';
import Card from '@/packages/card/doc.md?raw'
import TimeDetail from '@/packages/timedetail/doc.md?raw'
import TimeSelectzhTW from '@/packages/timeselect/doc.zh-TW.md?raw';
import TimeSelecttaro from '@/packages/timeselect/doc.taro.md?raw';
import TimeSelectenUS from '@/packages/timeselect/doc.en-US.md?raw';
import TimeSelect from '@/packages/timeselect/doc.md?raw'
import TrendArrowzhTW from '@/packages/trendarrow/doc.zh-TW.md?raw';
import TrendArrowtaro from '@/packages/trendarrow/doc.taro.md?raw';
import TrendArrowenUS from '@/packages/trendarrow/doc.en-US.md?raw';
import TrendArrow from '@/packages/trendarrow/doc.md?raw'
import WaterMarkzhTW from '@/packages/watermark/doc.zh-TW.md?raw';
import WaterMarktaro from '@/packages/watermark/doc.taro.md?raw';
import WaterMarkenUS from '@/packages/watermark/doc.en-US.md?raw';
import WaterMark from '@/packages/watermark/doc.md?raw'
import AvatarCropperzhTW from '@/packages/avatarcropper/doc.zh-TW.md?raw';
import AvatarCroppertaro from '@/packages/avatarcropper/doc.taro.md?raw';
import AvatarCropperenUS from '@/packages/avatarcropper/doc.en-US.md?raw';
import AvatarCropper from '@/packages/avatarcropper/doc.md?raw'

export const routers = ['Button','Cell','CellGroup','ConfigProvider','Image','Overlay','Col','Divider','Grid','GridItem','Layout','Row','Space','Sticky','SafeArea','BackTop','Elevator','FixedNav','NavBar','SideNavBar','SideNavBarItem','SubSideNavBar','Tabbar','TabbarItem','TabPane','Tabs','Address','Calendar','CalendarItem','CalendarCard','Cascader','Checkbox','CheckboxGroup','DatePicker','Form','FormItem','Input','InputNumber','Menu','MenuItem','NumberKeyboard','Picker','Radio','RadioGroup','Range','Rate','SearchBar','ShortPassword','Signature','Switch','TextArea','Uploader','ActionSheet','Badge','Dialog','Drag','Empty','InfiniteLoading','Loading','NoticeBar','Notify','Popover','Popup','PullToRefresh','Skeleton','Swipe','Toast','Animate','AnimatingNumbers','Audio','Avatar','AvatarGroup','CircleProgress','Collapse','CollapseItem','CountDown','Ellipsis','ImagePreview','Indicator','Pagination','Price','Progress','Step','Steps','Swiper','SwiperItem','Table','Tag','Tour','Video','VirtualList','Barrage','Card','TimeDetail','TimeSelect','TrendArrow','WaterMark','AvatarCropper']
export const raws = {ButtonzhTW,Buttontaro,ButtonenUS,Button,CellzhTW,Celltaro,CellenUS,Cell,CellGroup,ConfigProviderzhTW,ConfigProvidertaro,ConfigProviderenUS,ConfigProvider,ImagezhTW,Imagetaro,ImageenUS,Image,OverlayzhTW,Overlaytaro,OverlayenUS,Overlay,Col,DividerzhTW,Dividertaro,DividerenUS,Divider,GridzhTW,Gridtaro,GridenUS,Grid,GridItem,LayoutzhTW,Layouttaro,LayoutenUS,Layout,Row,SpacezhTW,Spacetaro,SpaceenUS,Space,StickyzhTW,Stickytaro,StickyenUS,Sticky,SafeAreazhTW,SafeAreataro,SafeAreaenUS,SafeArea,BackTopzhTW,BackToptaro,BackTopenUS,BackTop,ElevatorzhTW,Elevatortaro,ElevatorenUS,Elevator,FixedNavzhTW,FixedNavtaro,FixedNavenUS,FixedNav,NavBarzhTW,NavBartaro,NavBarenUS,NavBar,SideNavBarzhTW,SideNavBartaro,SideNavBarenUS,SideNavBar,SideNavBarItem,SubSideNavBar,TabbarzhTW,Tabbartaro,TabbarenUS,Tabbar,TabbarItem,TabPane,TabszhTW,Tabstaro,TabsenUS,Tabs,AddresszhTW,Addresstaro,AddressenUS,Address,CalendarzhTW,Calendartaro,CalendarenUS,Calendar,CalendarItem,CalendarCardzhTW,CalendarCardtaro,CalendarCardenUS,CalendarCard,CascaderzhTW,Cascadertaro,CascaderenUS,Cascader,CheckboxzhTW,Checkboxtaro,CheckboxenUS,Checkbox,CheckboxGroup,DatePickerzhTW,DatePickertaro,DatePickerenUS,DatePicker,FormzhTW,Formtaro,FormenUS,Form,FormItem,InputzhTW,Inputtaro,InputenUS,Input,InputNumberzhTW,InputNumbertaro,InputNumberenUS,InputNumber,MenuzhTW,Menutaro,MenuenUS,Menu,MenuItem,NumberKeyboardzhTW,NumberKeyboardtaro,NumberKeyboardenUS,NumberKeyboard,PickerzhTW,Pickertaro,PickerenUS,Picker,RadiozhTW,Radiotaro,RadioenUS,Radio,RadioGroup,RangezhTW,Rangetaro,RangeenUS,Range,RatezhTW,Ratetaro,RateenUS,Rate,SearchBarzhTW,SearchBartaro,SearchBarenUS,SearchBar,ShortPasswordzhTW,ShortPasswordtaro,ShortPasswordenUS,ShortPassword,SignaturezhTW,Signaturetaro,SignatureenUS,Signature,SwitchzhTW,Switchtaro,SwitchenUS,Switch,TextAreazhTW,TextAreataro,TextAreaenUS,TextArea,UploaderzhTW,Uploadertaro,UploaderenUS,Uploader,ActionSheetzhTW,ActionSheettaro,ActionSheetenUS,ActionSheet,BadgezhTW,Badgetaro,BadgeenUS,Badge,DialogzhTW,Dialogtaro,DialogenUS,Dialog,DragzhTW,Dragtaro,DragenUS,Drag,EmptyzhTW,Emptytaro,EmptyenUS,Empty,InfiniteLoadingzhTW,InfiniteLoadingtaro,InfiniteLoadingenUS,InfiniteLoading,LoadingzhTW,Loadingtaro,LoadingenUS,Loading,NoticeBarzhTW,NoticeBartaro,NoticeBarenUS,NoticeBar,NotifyzhTW,Notifytaro,NotifyenUS,Notify,PopoverzhTW,Popovertaro,PopoverenUS,Popover,PopupzhTW,Popuptaro,PopupenUS,Popup,PullToRefreshzhTW,PullToRefreshtaro,PullToRefreshenUS,PullToRefresh,SkeletonzhTW,Skeletontaro,SkeletonenUS,Skeleton,SwipezhTW,Swipetaro,SwipeenUS,Swipe,ToastzhTW,Toasttaro,ToastenUS,Toast,AnimatezhTW,Animatetaro,AnimateenUS,Animate,AnimatingNumberszhTW,AnimatingNumberstaro,AnimatingNumbersenUS,AnimatingNumbers,AudiozhTW,Audiotaro,AudioenUS,Audio,AvatarzhTW,Avatartaro,AvatarenUS,Avatar,AvatarGroup,CircleProgresszhTW,CircleProgresstaro,CircleProgressenUS,CircleProgress,CollapsezhTW,Collapsetaro,CollapseenUS,Collapse,CollapseItem,CountDownzhTW,CountDowntaro,CountDownenUS,CountDown,EllipsiszhTW,Ellipsistaro,EllipsisenUS,Ellipsis,ImagePreviewzhTW,ImagePreviewtaro,ImagePreviewenUS,ImagePreview,IndicatorzhTW,Indicatortaro,IndicatorenUS,Indicator,PaginationzhTW,Paginationtaro,PaginationenUS,Pagination,PricezhTW,Pricetaro,PriceenUS,Price,ProgresszhTW,Progresstaro,ProgressenUS,Progress,Step,StepszhTW,Stepstaro,StepsenUS,Steps,SwiperzhTW,Swipertaro,SwiperenUS,Swiper,SwiperItem,TablezhTW,Tabletaro,TableenUS,Table,TagzhTW,Tagtaro,TagenUS,Tag,TourzhTW,Tourtaro,TourenUS,Tour,VideozhTW,Videotaro,VideoenUS,Video,VirtualListzhTW,VirtualListtaro,VirtualListenUS,VirtualList,BarragezhTW,Barragetaro,BarrageenUS,Barrage,CardzhTW,Cardtaro,CardenUS,Card,TimeDetail,TimeSelectzhTW,TimeSelecttaro,TimeSelectenUS,TimeSelect,TrendArrowzhTW,TrendArrowtaro,TrendArrowenUS,TrendArrow,WaterMarkzhTW,WaterMarktaro,WaterMarkenUS,WaterMark,AvatarCropperzhTW,AvatarCroppertaro,AvatarCropperenUS,AvatarCropper}
