name: Release 3.x

on:
  push:
    tags:
      - v3.*
  workflow_dispatch:

jobs:
  release-3x:
    env:
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      NPM_CONFIG_PROVENANCE: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm i -g pnpm@10

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        if: env.ABORT != 'true'
        run: |
          if ! pnpm build; then
            echo "构建 nutui-react 失败"
            exit 1
          fi
          if ! pnpm build:taro; then
            echo "构建 nutui-react-taro 失败"
            exit 1
          fi

      - name: Run Release @nutui/nutui-react
        if: env.ABORT != 'true'
        run: |
          cd ./release/h5 || exit 1
          if ! npm publish --tag ${{ env.RELEASE_TAG }}; then
            echo "发布 @nutui/nutui-react 失败"
            exit 1
          fi

      - name: Run Releases @nutui/nutui-react-taro
        if: env.ABORT != 'true'
        run: |
          cd ./release/taro || exit 1
          if ! npm publish --tag ${{ env.RELEASE_TAG }}; then
            echo "发布 @nutui/nutui-react-taro 失败"
            exit 1
          fi
