name: Release Beta NPM Packages

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Publish release packages version'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - alpha
      publish:
        description: 'Test scenario tags (true or false)'
        required: true
        type: string
        default: 'false'

jobs:
  release-beta:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_CONFIG_PROVENANCE: true
      TAG: ${{ inputs.tags }}

    runs-on: ubuntu-latest
    if: ${{ inputs.publish == 'true' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm@v9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Build
        run: pnpm build && pnpm build:taro

      - name: Run Release @nutui/nutui-react
        run: cd ./release/h5 && npm publish --dry-run --tag $TAG

      - name: Run Releases @nutui/nutui-react-taro
        run: cd ./release/taro && npm publish --dry-run --tag $TAG