name: Release 3x Beta NPM Packages

on:
  push:
    branches:
      - feat_v3.x
  pull_request:
    branches:
      - feat_v3.x

jobs:
  release-beta:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_CONFIG_PROVENANCE: true

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get commit message
        run: |
          COMMIT_MESSAGE=$(git log --format=%s -n 1)
          echo "COMMIT_MESSAGE=${COMMIT_MESSAGE}" >> $GITHUB_ENV
      - name: Show commit message
        run: echo "$COMMIT_MESSAGE"

      - name: Commit message compliance verification
        if: startsWith( env.COMMIT_MESSAGE , 'chore(release):' ) != true
        run: echo "ABORT=true" >> $GITHUB_ENV

      - name: Get Tag message
        if: contains( env.COMMIT_MESSAGE , '-beta')
        run: echo "RELEASE_TAG=beta" >> $GITHUB_ENV

      - name: Install pnpm
        run: npm install -g pnpm@v9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        if: env.ABORT != 'true'
        run: pnpm install --no-frozen-lockfile

      - name: Run Build
        if: env.ABORT != 'true'
        run: pnpm build && pnpm build:taro

      - name: Run Release @nutui/nutui-react
        if: env.ABORT != 'true'
        run: cd ./release/h5 && npm publish --dry-run --tag beta

      - name: Run Releases @nutui/nutui-react-taro
        if: env.ABORT != 'true'
        run: cd ./release/taro && npm publish --dry-run --tag beta