name: Release 3x Beta NPM Packages

on:
  push:
    branches:
      - feat_v3.x
  pull_request:
    branches:
      - feat_v3.x

jobs:
  release-beta:
    if: |
      github: release.event.head_commit_master != null &&
      startsWith(github.event.head_commit.message, 'chore(release): ') &&
      contains(github.event.head_commit.message, '-beta.')
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_CONFIG_PROVENANCE: true
      TAG: ${{ inputs.tags }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        run: npm install -g pnpm@v9

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run Build
        run: pnpm build && pnpm build:taro

      - name: Run Release @nutui/nutui-react
        run: cd ./release/h5 && npm publish --dry-run --tag beta

      - name: Run Releases @nutui/nutui-react-taro
        run: cd ./release/taro && npm publish --dry-run --tag beta