name: Sync to Gitee

on:
  push:
    branches: [main]

jobs:
  deploy-site-sync-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:jdf2e/nutui-react.git
          destination-repo: git@gitee.com:jd-platform-opensource/nutui-react.git
