name: Sync to Gitcode

on:
  push:
    branches: ['1.x-stable']

jobs:
  deploy-site-sync-gitcode:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitcode
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:jdf2e/nutui-react.git
          destination-repo: git@gitcode.net:jd/nutui-react.git
