name: Test Pull Request Review

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

permissions:
  pull-requests: write
  issues: write

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: echo "${{ toJSON(github.event.review) }}"

      - name: Update PR labels
        run: |
          LABEL_NAME="Test"  # 替换为你想要添加的标签名称
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}

          curl -X POST \
               -H "Authorization: token ${{ secrets.FOR_PULL_REVIEW }}" \
               -H "Accept: application/vnd.github.v3+json" \
               -d "{\"labels\": [\"$LABEL_NAME\"]}" \
               https://api.github.com/repos/$REPO/issues/$PR_NUMBER/labels