name: Test Pull Request Review

on:
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed

jobs:
  approved:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.event.review.state }}"

